package telas_system;

import classes_banco.Conexao_db;
import classes_basic.Editora;
import classes_basic.GerenciarEditora;
import classes_basic.Informacoes;
import com.mysql.jdbc.Connection;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Tela_Editora extends javax.swing.JFrame {
    Conexao_db conexao;
    Connection con;
    GerenciarEditora ger_editora;
    
    String sql = "select *from editora order by nome_editora";
    /**
     * Creates new form Tela_Editora
     */
    public Tela_Editora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbEditar = new javax.swing.JLabel();
        lbNova = new javax.swing.JLabel();
        lbExcluir = new javax.swing.JLabel();
        lbRedefinir = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescricao = new javax.swing.JTextArea();
        tfAno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Editora");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lbEditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbEditar.setForeground(new java.awt.Color(255, 255, 255));
        lbEditar.setText("Editar");
        lbEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEditarMouseClicked(evt);
            }
        });

        lbNova.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNova.setForeground(new java.awt.Color(255, 255, 255));
        lbNova.setText("Nova");
        lbNova.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNovaMouseClicked(evt);
            }
        });

        lbExcluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lbExcluir.setText("Excluir");
        lbExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExcluirMouseClicked(evt);
            }
        });

        lbRedefinir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbRedefinir.setForeground(new java.awt.Color(255, 255, 255));
        lbRedefinir.setText("Redefinir");
        lbRedefinir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRedefinir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRedefinirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbRedefinir)
                .addGap(18, 18, 18)
                .addComponent(lbNova)
                .addGap(18, 18, 18)
                .addComponent(lbEditar)
                .addGap(18, 18, 18)
                .addComponent(lbExcluir)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNova)
                    .addComponent(lbEditar)
                    .addComponent(lbExcluir)
                    .addComponent(lbRedefinir))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

        painel2.setBackground(new java.awt.Color(0, 0, 0, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDITORAS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ano de Fundação:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descrição:");

        tfNome.setBackground(new java.awt.Color(0, 0, 0));
        tfNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfNome.setForeground(new java.awt.Color(255, 255, 255));

        tfDescricao.setBackground(new java.awt.Color(0, 0, 0));
        tfDescricao.setColumns(20);
        tfDescricao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfDescricao.setForeground(new java.awt.Color(255, 255, 255));
        tfDescricao.setRows(5);
        jScrollPane1.setViewportView(tfDescricao);

        tfAno.setBackground(new java.awt.Color(0, 0, 0));
        tfAno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfAno.setForeground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Ano de Fundação", "Descrição"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel2)
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(painel2Layout.createSequentialGroup()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(tfNome)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 610, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plano-de-fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        setSize(new java.awt.Dimension(717, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Ao abrir a tela:
        conexao = new Conexao_db();

        try {
            con = (Connection) conexao.Conectar();
            PreencherTabela(sql);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Tela_Categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // Ao fechar a tela:
            conexao.Conectar();
        } catch (IOException ex) {
            Logger.getLogger(Tela_Editora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // Ao clicar na tabela (quando se clica na linha da tabela aparece os dados completos do uuário)
        int linha = tabela.getSelectedRow();
        
        tfNome.setText(tabela.getValueAt(linha,1).toString());
        tfAno.setText(tabela.getValueAt(linha,2).toString());
        tfDescricao.setText(tabela.getValueAt(linha,3).toString());
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void lbNovaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovaMouseClicked
        // Ao clicar em nova:
        String nome = String.valueOf(tfNome.getText());
        String ano = String.valueOf(tfAno.getText());
        String descricao = String.valueOf(tfDescricao.getText());
        
        
        Editora editora = new Editora();
        editora.setAno_fundacao(ano);
        editora.setNome_editora(nome);
        editora.setDescricao(descricao);
        editora.setId_editora(0);
        
        ger_editora = new GerenciarEditora();
        
        if (nome.length()>0 && ano.length()>0 && descricao.length()>0){
            try {
                if(ger_editora.VerificarEditora(con,editora) == false){
                    ger_editora.AddEditora(con,editora);
                    JOptionPane.showMessageDialog(null, "Editora cadastrada com sucesso", "Editora cadastrada!",1);
                    PreencherTabela(sql);
                } else { 
                    JOptionPane.showMessageDialog(null, "Editora já está cadastrada!", "Erro!",2);
                }
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(Tela_Editora.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos", "Erro!",2);
        }
        
        
    }//GEN-LAST:event_lbNovaMouseClicked

    private void lbEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEditarMouseClicked
        //Ao clicar em editar:
        String nome = String.valueOf(tfNome.getText());
        String ano = String.valueOf(tfAno.getText());
        String descricao = String.valueOf(tfDescricao.getText());
        
        int linha = tabela.getSelectedRow();  
        Integer id = Integer.parseInt(tabela.getValueAt(linha,0).toString());
        
        Editora editora = new Editora();
        editora.setAno_fundacao(ano);
        editora.setNome_editora(nome);
        editora.setDescricao(descricao);
        editora.setId_editora(id);
        
        ger_editora = new GerenciarEditora();
        if (nome.length()>0 && ano.length()>0 && descricao.length()>0){
            try {
                ger_editora.AltEditora(con,editora);
                JOptionPane.showMessageDialog(null, "Editora alterada com sucesso", "Editora alterada!",1);
                PreencherTabela(sql);
                
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(Tela_Editora.class.getName()).log(Level.SEVERE, null, ex);
            }  
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos", "Erro!",2);
        }
        
    }//GEN-LAST:event_lbEditarMouseClicked

    private void lbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExcluirMouseClicked
        int linha = tabela.getSelectedRow();  
        Integer id = Integer.parseInt(tabela.getValueAt(linha,0).toString());
        
        Editora editora = new Editora();
        editora.setId_editora(id);
        
        Object[] options = { "Sim", "Não" };
        int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir esta categoria?", "Excluir categoria", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        System.out.println("Opcao: " + opcao);
        
        if(opcao == 0){
            try {
                ger_editora.DelEditora(con,editora);
                JOptionPane.showMessageDialog(null, "A conta foi excluída com sucesso!", "Conta Excluída!", 1);
                PreencherTabela(sql);
                
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Editora.class.getName()).log(Level.SEVERE, null, ex);
            }  
        } 
    }//GEN-LAST:event_lbExcluirMouseClicked

    private void lbRedefinirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRedefinirMouseClicked
        // Ao clicar em redefinir:
        tfAno.setText("");
        tfDescricao.setText("");
        tfNome.setText("");
        
    }//GEN-LAST:event_lbRedefinirMouseClicked
    public void PreencherTabela(String sql) throws SQLException{ 
       PreparedStatement stmt = con.prepareStatement(sql);
       ResultSet rs = stmt.executeQuery(); //Resultado do banco de dados
       
       //Gravando as informações da tabela no banco de dados
       DefaultTableModel modelo = (DefaultTableModel)tabela.getModel();
       modelo.setNumRows(0);
       
       while(rs.next()) {
          modelo.addRow(new Object[]
          {
              rs.getInt("id_editora"),
              rs.getString("nome_editora"),
              rs.getString("ano_fundacao"),
              rs.getString("descricao"),
          });
       
     } //Fim while
      rs.close();
      stmt.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Editora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Editora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEditar;
    private javax.swing.JLabel lbExcluir;
    private javax.swing.JLabel lbNova;
    private javax.swing.JLabel lbRedefinir;
    private javax.swing.JPanel painel2;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextArea tfDescricao;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
